[tool.ruff]
# Set the line length to match Black.
line-length = 88

[tool.ruff.lint]
# E501: Line too long
ignore = ["E501"]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
select = ["E4", "E7", "E9", "F", "I"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
